const Projects = [
    {
        id: '1',
        slug: 'Maria-Robin',
        title:'Maria & Robin',
        pimg1:'/images/portfolio/1.jpg',
        pSimg:'/images/portfolio-single/1.jpg',
        date:'Feb 2019',
        location:'Austria',
    },
    {
        id: '2',
        slug: 'Rose-Harry',
        title:'Rose & Harry',
        pimg1:'/images/portfolio/2.jpg',
        pSimg:'/images/portfolio-single/2.jpg',
        date:'Jan 2019',
        location:'Austria',
    },
    {
        id: '3',
        slug: 'Aliana-David',
        title:'Aliana & David',
        pimg1:'/images/portfolio/3.jpg',
        pSimg:'/images/portfolio-single/3.jpg',
        date:'Mar 2020',
        location:'Austria',
    },
    {
        id: '4',
        slug: 'Aliza-Ken',
        title:'Aliza & Ken',
        pimg1:'/images/portfolio/4.jpg',
        pSimg:'/images/portfolio-single/4.jpg',
        date:'Apr 2020',
        location:'Austria',
    },
    {
        id: '5',
        slug: 'Michel-Dianee',
        title:'Michel & Dianee',
        pimg1:'/images/portfolio/5.jpg',
        pSimg:'/images/portfolio-single/5.jpg',
        date:'Jan 2022',
        location:'Austria',
    },
    {
        id: '6',
        slug: 'Maria-Nepela',
        title:'Maria & Nepela',
        pimg1:'/images/portfolio/61.jpg',
        pSimg:'/images/portfolio-single/6.jpg',
        date:'Jun 2022',
        location:'Austria',
    },
    {
        id: '7',
        slug: 'Maria-Nevela',
        title:'Maria & Nevela',
        pimg1:'/images/portfolio/6.jpg',
        pSimg:'/images/portfolio-single/7.jpg',
        date:'Jun 2022',
        location:'Austria',
    }
]
export default Projects;